// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SemanticPreflight = { semanticMode: boolean, semanticModeVersion: string, runtimeVersion: string, model: string, modelProvider: string, toolPolicy: string, effectiveToolCount: number, toolManifestDigest: string, instructionPolicy: string, outputSchemaStrict: boolean, authenticated: boolean, authMode: string, authStoreKind: string, sessionMode: string, requestedCodexTurns: number, requestAccounting: string, };
